name: oltinchi_oy_imtihon_oddiygina
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  lottie: ^3.1.3
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "logo/logo.png"
  windows:
    generate: true
    image_path: "logo/logo.png"
    icon_size: 48

flutter_native_splash:
  image: assets/logo/logo.png
  color: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - lottifor/
    - logo/logo.png
